project:
  type: book

book:
  title: "Logic Programming"
  author: "Igor Dimitrov"
  date: "5/17/2024"
  chapters:
    - index.qmd
    - reading.qmd
    - part: "Prolog"
      chapters:
      - prolog/intro.qmd
  page-navigation: true
  downloads: pdf

bibliography: references.bib

csl: nature.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



